### ISSUE TITLE
Mock doesn't work when calling hidden functions

### ISSUE THREAD

**Issue by kjohnsen** [krlmlr/mockr#4]
In my package I have these functions defined:
```r
helperFunc <- function() { FALSE }
.myFunc <- function() { helperFunc() }
```

In my test, I have the following, so that the test will fail if the mock isn't called:
```r
.mockHelperFunc <- function() { TRUE }

test_that('with_mock works', {
    result <- mockr::with_mock(
        helperFunc=.mockHelperFunc,
        .myFunc()
    )
    expect_true(result)
})
```

I run the test, and it fails, meaning `.myFunc` didn't call the mock as expected. However, when I change `.myFunc` to `myFunc`, i.e., make it no longer a hidden function, the test works fine. Is this expected behavior? This unexpectedly broke my tests when switching from `testthat::with_mock` to `mockr::with_mock`.

**Comment by petermeissner** [comment]
*Just a short comment on the side completely unrelated to solving the problem:*

Using 'hidden functions' is almost always a bad idea. There are solid methods for controlling what users and external packages are allowed to access from a package via doing explicit exports in the NAMESPACE file or using the `@export` flag with `roxygen` (see here, e.g.: http://r-pkgs.had.co.nz/namespace.html#Exports)

**Comment by krlmlr** [comment]
Thanks. Indeed:

``` r
helperFunc <- function() {
  FALSE
}
.myFunc <- function() {
  helperFunc()
}

.mockHelperFunc <- function() {
  TRUE
}

testthat::test_that("with_mock works", {
  result <- mockr::with_mock(
    helperFunc = .mockHelperFunc,
    .myFunc()
  )
  testthat::expect_true(result)
})
#> ── FAILURE (<text>:17:3): with_mock works ──────────────────────────────────────
#> `result` is not TRUE
#> 
#> `actual`:   FALSE
#> `expected`: TRUE
```

<sup>Created on 2020-12-11 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

I'll take a look.
