### ISSUE TITLE
Think about interactive case

### ISSUE THREAD

**Issue by hadley** [krlmlr/mockr#7]
Taking this test from usethis:

```R
test_that("use_pkgdown() creates and ignores the promised file/dir", {
  create_local_package()
  mockr::with_mock(
    is_installed = function(pkg) TRUE,
    use_pkgdown()
  )
  expect_true(uses_pkgdown())
  expect_true(is_build_ignored("^_pkgdown\\.yml$"))
  expect_true(is_build_ignored("^docs$"))
})
```

If I run it interactively, I get:

```
── Error (Line 3): use_pkgdown() creates and ignores the promised file/dir ───────
Error: is_installed not found in environment R_GlobalEnv.
Backtrace:
  1. mockr::with_mock(is_installed = function(pkg) TRUE, use_pkgdown())
  2. mockr:::with_mock_(.dots = .dots, .parent = .parent, .env = .env)
  3. mockr:::create_mock_env_(...)
  4. mockr:::extract_new_funcs_(dots, .env)
  5. mockr:::extract_mocks(dots = dots, env = .env)
  6. base::lapply(...)
  7. mockr:::FUN(X[[i]], ...)
  8. mockr:::extract_mock(qual_name, dots[[qual_name]], env)
  9. mockr:::check_mock(name, env)
 10. mockr:::stopc(...)
```

which is true, but annoying. 

Maybe if `testthat::testing_package()` is `""` mockr could relax the rules to modify any environment on the search path that has been attached by load all?

**Comment by krlmlr** [comment]
Thanks, confirmed. I'll take a look.

**Comment by krlmlr** [comment]
When run interactively `testing_package()` is still `""`. Looking for `load_all()` environments seems like a good idea, I think we should only do this if the current `topenv()` doesn't have the functions that the caller wants to mock.

Overall use cases:

- [ ] `test_that()` running a test
- [ ] examples
- [ ] standalone script
- [ ] rmarkdown (for documentation)
- [ ] `test_that()` running locally
