### ISSUE TITLE
Example of writing a wrapper

### ISSUE THREAD

**Issue by 1beb** [krlmlr/mockr#8]
Hi @krlmlr good work with this package! I use the version that's currently baked into testthat signficantly. On to my question: 

> Mocking external functions (in other packages) doesn't work anymore. This is by design.

You suggest that we should "write a wrapper" to solve situations like this. Could you provide an example? 

Here's an example of something I used to do: 

```
test_that("Some multistep end-end test", {
   res <- with_mock(
         actual_function(...),
         `package::functionA` = function() 200,
         `package::functionB` = function() 200
   )
   # test expectations on res ...
})
```

How would you approach this with mockr?

**Comment by nbenn** [comment]
@1beb I might be wrong here, but I think the idea is that in your package you write wrapper functions

```r
my_fun_a <- function(...) package::functionA(...)
my_fun_b <- function(...) package::functionB(...)
```

and then you go ahead and mock these wrappers in your tests

```r
res <- with_mock(
  actual_function(...),
  my_fun_a = function(...) 200,
  my_fun_b = function(...) 200
)
```

**Comment by krlmlr** [comment]
Thanks @1beb for raising this and @nbenn for the example. I think we could describe this in the README, would anyone like to take a stab?
