### ISSUE TITLE
S3 dispatch

### ISSUE THREAD

**Issue by nbenn** [krlmlr/mockr#9]
It seems to me as though things do not work as expected in the context of S3 dispatch:

```r
gen <- function(x) UseMethod("gen")

met <- function(x) foo(x)

foo <- function(x) stop("foo")

.S3method("gen", "cls", met)

x <- structure(123, class = "cls")

gen(x)
#> Error in foo(x) : foo

test_gen <- function() {
  mockr::with_mock(
    foo = function(x) "bar",
    gen(x)
  )
}

test_gen()
#> Error in foo(x) : foo

test_met <- function() {
  mockr::with_mock(
    foo = function(x) "bar",
    met(x)
  )
}

test_met()
#> [1] "bar"
```

Is this a known limitation of `mockr::with_mock()`?

**Comment by krlmlr** [comment]
Thanks. Yeah, mockr doesn't modify the S3 method table. Should it?

**Comment by krlmlr** [comment]
Good job on mockthat, does that make mockr obsolete?

**Comment by nbenn** [comment]
> Thanks. Yeah, mockr doesn't modify the S3 method table. Should it?

Idk, for a test scenario of mine, I needed this functionality. As I already had to start changing more and more of my code mainly due to the "external-functions" limitation, I at some point decided to look into alternative approaches.

> Good job on mockthat

Thanks!

> does that make mockr obsolete?

Well, I was trying to come up with a solution that would make both 'mockr' and 'mockery' obsolete in the sense that there is no scenario that either of the two can handle, which does not work with the 'mockthat' approach (while of course removing some of the limitations of the other two approaches).

But keep in mind that 'mockthat' so far has seen little real-world use. If no major issues pop up then yes, it was my hope to make 'mockr' obsolete by offering a solution that is as flexible as the original 'testthat' implementation without the downside of violating the C API.

**Comment by krlmlr** [comment]
Thanks. The other way to "mock" S3 methods is to implement a subclass and relevant methods for that subclass, I have done so in pillar and tibble.
